# Architectures from wavlm_km.yaml + flow_wo_dp.yaml.
sample_rate: 24000
speech_vocab_size: 1024
spk_embed_dim: 256
flow_embed_dim: 512
feat_dim: 80

quantizer: !new:dlm_an.model.ssl_quant.kmeans.SslMiniBatchKMeans
    ssl_extractor: !new:dlm_an.model.ssl_wrapper.wavlm_extractor.WavLMExtractor
        model_name: microsoft/wavlm-large
        layer: 22
        normalize_wav: True
        padding: False
    dim: 1024
    n_clusters: 1024
    init: k-means++
    n_init: 20
    tol: 0.0
    max_no_improvement: 10
    num_dataset_samples: 90000000
    reassignment_ratio: 0.0
    verbose: 0

flow: !new:dlm_an.model.flow.dit_flow.DiTFlow
    embed_dim: !ref <flow_embed_dim>
    token_vocab_size: !ref <speech_vocab_size>
    spk_embed_dim: !ref <spk_embed_dim>
    token_encoder: !new:dlm_an.transformer.encoder.ConformerEncoder
        input_size: !ref <flow_embed_dim>
        output_size: !ref <flow_embed_dim>
        attention_heads: 8
        linear_units: 2048
        num_blocks: 8
        dropout_rate: 0.1
        positional_dropout_rate: 0.1
        attention_dropout_rate: 0.1
        normalize_before: True
        input_layer: linear
        pos_enc_layer_type: rel_pos_espnet
        selfattention_layer_type: rel_selfattn
        use_cnn_module: False
        macaron_style: False
    length_regulator: !new:dlm_an.model.flow.length_regulator.LengthRegulator
    duration_predictor: null
    speech_decoder: !new:dlm_an.model.dit.dit_speech_encoder.DiTSpeechEncoder
        cond_dim: !ref <flow_embed_dim>
        output_dim: !ref <feat_dim>
        spk_dim: !ref <spk_embed_dim>
        embed_dim: !ref <flow_embed_dim>
        num_heads: 8
        num_layers: 6
        postnet_mult: 2
        postnet_dim: 128
        dropout_rate: 0.1
        cond_cfg_rate: 0.2
        spk_cfg_rate: 0.2

hift: !new:dlm_an.model.hift.generator.HiFTGenerator
    in_channels: 80
    base_channels: 512
    nb_harmonics: 8
    sampling_rate: !ref <sample_rate>
    nsf_alpha: 0.1
    nsf_sigma: 0.003
    nsf_voiced_threshold: 10
    upsample_rates: [8, 5, 3]
    upsample_kernel_sizes: [16, 11, 7]
    istft_params: {n_fft: 16, hop_len: 4}
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    source_resblock_kernel_sizes: [7, 7, 11]
    source_resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    lrelu_slope: 0.1
    audio_limit: 0.99
    f0_predictor: !new:dlm_an.model.hift.f0_predictor.ConvRNNF0Predictor
        num_class: 1
        in_channels: 80
        cond_channels: 512